version: '3.8'

services:
  app:
    build: .
    container_name: nodejs_app
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./keys:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 